package com.redhat.demos.imagegapanalysis;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IMDBResult implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public IMDBResult() {
    }

}