package com.redhat.demos.imagegapanalysis;

/**
 * This class was automatically generated by the data modeler tool
 */

public class MovieEpisodeRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label("Air Date")
   private String airDate;
   @org.kie.api.definition.type.Label("Release Year")
   private java.lang.String releaseYear;
   @org.kie.api.definition.type.Label("Synopsis")
   private java.lang.String synopsis;

   @org.kie.api.definition.type.Label("Poster URL")
   private java.lang.String posterURL;

   @org.kie.api.definition.type.Label(value = "Country")
   private java.lang.String country;

   public MovieEpisodeRequest()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public String getAirDate()
   {
      return this.airDate;
   }

   public void setAirDate(String airDate)
   {
      this.airDate = airDate;
   }

   public java.lang.String getReleaseYear()
   {
      return this.releaseYear;
   }

   public void setReleaseYear(java.lang.String releaseYear)
   {
      this.releaseYear = releaseYear;
   }

   public java.lang.String getSynopsis()
   {
      return this.synopsis;
   }

   public void setSynopsis(java.lang.String synopsis)
   {
      this.synopsis = synopsis;
   }

   public java.lang.String getPosterURL()
   {
      return this.posterURL;
   }

   public void setPosterURL(java.lang.String posterURL)
   {
      this.posterURL = posterURL;
   }

   public static String encodeString(String toEncode)
   {
      String toReturn = "no%20value";
      toReturn = toEncode.replaceAll("\\s+", "%20");
      return toReturn;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public MovieEpisodeRequest(java.lang.Integer id, java.lang.String name,
         java.lang.String type, java.lang.String airDate,
         java.lang.String releaseYear, java.lang.String synopsis,
         java.lang.String posterURL, java.lang.String country)
   {
      this.id = id;
      this.name = name;
      this.type = type;
      this.airDate = airDate;
      this.releaseYear = releaseYear;
      this.synopsis = synopsis;
      this.posterURL = posterURL;
      this.country = country;
   }

}
